# Generated by Django 4.1 on 2022-08-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entregable1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familiares',
            new_name='modelo_familiares',
        ),
    ]
