# Generated by Django 4.1 on 2022-08-22 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Entregable1', '0002_rename_familiares_modelo_familiares'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo_familiares',
            name='horario_consulta',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
